/*
CODE사전용 VIEW
*/
CREATE VIEW [dbo].[uvCODE_VIEW]
AS 
SELECT 
	A.CODE_CATE_NO
,	A.CATE_NM
,	B.CODE
,	B.CODE_NM
FROM DBO.CODE_CATES A
JOIN DBO.CODE_DICT B
	ON B.CODE_CATE_NO = A.CODE_CATE_NO
WHERE A.IS_DEL = 0
AND B.IS_DEL = 0
;