USE DEV
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.upBOARD_UPDATE') AND type in (N'P', N'PC'))
	DROP PROCEDURE dbo.upBOARD_UPDATE
GO

/*
upUSER_UPDATE 
*/
CREATE PROCEDURE [dbo].[upBOARD_UPDATE]
(
	@CMD			CHAR(1)
,	@BOARD_TYPE_CD	VARCHAR(10)		--게시물 분류 코드
,	@BOARD_NO		INT				= NULL
,	@UP_BOARD_NO	INT				= NULL
,	@USER_NO		INT
,	@TITLE			VARCHAR(100)
,	@CONT			VARCHAR(MAX)
,	@RESULT			INT			OUTPUT
,	@NEW_BOARD_NO	INT	= NULL	OUTPUT
)
AS
SET NOCOUNT ON;

IF @CMD = 'I'
BEGIN
	
	INSERT INTO DBO.BOARDS
	(
		[BOARD_TYPE_CD], [UP_BOARD_NO], [USER_NO], [TITLE], [CONT], [IS_DEL], [LAST_CHNG_DT], [LAST_USER_NO]
	)
	VALUES
	(
		@BOARD_TYPE_CD, @UP_BOARD_NO, @USER_NO, @TITLE, @CONT, 0, GETDATE(), @USER_NO
	);

	SET @RESULT = @@ROWCOUNT;
	SET @NEW_BOARD_NO = SCOPE_IDENTITY();

END
ELSE IF @CMD = 'U'
BEGIN

	UPDATE A
	SET A.TITLE = @TITLE
	,	A.CONT	= @CONT
	,	A.LAST_CHNG_DT = GETDATE()
	,	A.LAST_USER_NO = @USER_NO
	FROM DBO.BOARDS A
	WHERE A.BOARD_NO = @BOARD_NO;

	SET @RESULT = @@ROWCOUNT;

END
ELSE IF @CMD = 'D'
BEGIN

	UPDATE A
	SET A.IS_DEL = 1
	,	A.LAST_CHNG_DT = GETDATE()
	,	A.LAST_USER_NO = @USER_NO
	FROM DBO.BOARDS A
	WHERE A.BOARD_NO = @BOARD_NO;

	SET @RESULT = @@ROWCOUNT;
END

RETURN @RESULT;