USE DEV
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.upBOARD_ATACH_FILES_UPDATE') AND type in (N'P', N'PC'))
	DROP PROCEDURE dbo.upBOARD_ATACH_FILES_UPDATE
GO

/*
upUSER_UPDATE 

SET @ATACH_FILES = '
[
{"FILE_NM":"AAAA.JPG,"FILE_SIZE":25544},
{"FILE_NM":"BBBB.JPG,"FILE_SIZE":12222}
]';

*/
CREATE PROCEDURE [dbo].[upBOARD_ATACH_FILES_UPDATE]
(
	@CMD			CHAR(1)
,	@USER_NO		INT
,	@BOARD_NO		INT	
,	@ATACH_FILES	VARCHAR(MAX)	= NULL
,	@RESULT			INT	OUTPUT
,	@RESULT_MESG	VARCHAR(100) = ''	OUTPUT
)
AS
SET NOCOUNT ON;

DECLARE
@OLD_CNT		INT

DECLARE @TMP TABLE
(
	ATACH_NO	INT
,	FILE_NM		VARCHAR(255)
,	FILE_SIZE	INT
);
INSERT INTO @TMP
SELECT
	ATACH_NO
,	FILE_NM		
,	FILE_SIZE	
FROM  OPENJSON(@ATACH_FILES)
WITH ( 
	ATACH_NO	INT
,	FILE_NM		VARCHAR(255)
,	FILE_SIZE	INT
);
SET @OLD_CNT = @@ROWCOUNT;

IF @CMD = 'I'
BEGIN
	INSERT INTO DBO.BOARD_ATACH_FILES
	(	
		[BOARD_NO], [FILE_NM], [FILE_SIZE], [DOWN_CNT], [LAST_CHNG_DT], [LAST_USER_NO]
	)
	SELECT
		@BOARD_NO
	,	A.FILE_NM
	,	A.FILE_SIZE
	,	0	
	,	GETDATE()
	,	@USER_NO
	FROM @TMP A;
	
	SET @RESULT = @@ROWCOUNT;
END
ELSE IF @CMD = 'D'
BEGIN
	DELETE FROM DBO.BOARD_ATACH_FILES
	WHERE ATACH_NO IN (SELECT ATACH_NO FROM @TMP)
	AND BOARD_NO = @BOARD_NO
	;
	SET @RESULT = @@ROWCOUNT;
END

--처리건수가 틀리면 오류처리
IF @OLD_CNT != @RESULT
BEGIN	
	SET @RESULT = -1;
	SET @RESULT_MESG = '전달된 파일목록과 처리된 파일건수가 틀립니다.';
END

RETURN @RESULT;