USE DEV
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.upUSER_LIST') AND type in (N'P', N'PC'))
	DROP PROCEDURE dbo.upUSER_LIST
GO

/*
upUSER_UPDATE 
*/

CREATE PROCEDURE [dbo].[upUSER_LIST]
(
	@USER_NO		INT
,	@SEARCH_KEY		VARCHAR(100)	= ''
,	@PAGE			INT = 1		--조회 PAGE
,	@CNT_PAGE		INT = 20	--PAGE당 조회건수
)
AS
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;	


SELECT
	A.[USER_NO]
,	A.[USER_NM]
,	A.[ID]
,	A.[PW]
,	A.[HDPH_NO]
,	A.[EMAIL]
,	COUNT(*) OVER() MAC_CNT
FROM DBO.USERS A
WHERE A.[IS_DEL] = 0
AND (
		@SEARCH_KEY = ''
		OR
		(
			A.[USER_NM] LIKE '%'+@SEARCH_KEY+'%'
			OR
			A.[ID] LIKE '%'+@SEARCH_KEY+'%'
			OR
			A.[HDPH_NO] LIKE '%'+@SEARCH_KEY+'%'
			OR
			A.[EMAIL] LIKE '%'+@SEARCH_KEY+'%'
		)
	)
ORDER BY A.[USER_NO] DESC
OFFSET ((@PAGE-1) * @CNT_PAGE) ROWS
FETCH NEXT @CNT_PAGE ROWS ONLY
;

