USE DEV
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.upUSER_UPDATE') AND type in (N'P', N'PC'))
	DROP PROCEDURE dbo.upUSER_UPDATE
GO

/*
upUSER_UPDATE 
*/
CREATE PROCEDURE [dbo].[upUSER_UPDATE]
(
	@CMD			CHAR(1)
,	@USER_NM		VARCHAR(30)
,	@ID				VARCHAR(20)
,	@PW				VARCHAR(20)
,	@HDPH_NO		VARCHAR(20)
,	@EMAIL			VARCHAR(50)
,	@USER_NO		INT				= NULL
,	@RESULT			INT	OUTPUT
)
AS
SET NOCOUNT ON;

IF @CMD = 'I'
BEGIN
	INSERT INTO DBO.USERS
	(
		[USER_NM], [ID], [PW], [HDPH_NO], [EMAIL], [IS_DEL], [LAST_CHNG_DT], [LAST_USER_NO]
	)
	VALUES
	(
		@USER_NM, @ID, @PW, @HDPH_NO, @EMAIL, 0, GETDATE(), 0
	);

	SET @RESULT = @@ROWCOUNT;
END
ELSE IF @CMD = 'U'
BEGIN
	UPDATE DBO.USERS
	SET [USER_NM]	= @USER_NM
	,	[ID]		= @ID
	,	[PW]		= @PW
	,	[HDPH_NO]	= @HDPH_NO
	,	[EMAIL]		= @EMAIL
	,	[LAST_CHNG_DT]	= GETDATE()
	,	[LAST_USER_NO]	= @USER_NO
	WHERE USER_NO = @USER_NO;

	SET @RESULT = @@ROWCOUNT;
END
ELSE IF @CMD = 'D'
BEGIN
	UPDATE DBO.USERS
	SET IS_DEL = 1
	,	[LAST_CHNG_DT]	= GETDATE()
	,	[LAST_USER_NO]	= @USER_NO
	WHERE USER_NO = @USER_NO;

	SET @RESULT = @@ROWCOUNT;
END

RETURN @RESULT;
