USE DEV
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.upUSER_SELECT') AND type in (N'P', N'PC'))
	DROP PROCEDURE dbo.upUSER_SELECT
GO

/*
upUSER_SELECT 
*/

CREATE PROCEDURE [dbo].[upUSER_SELECT]
(
	@USER_NO		INT
)
AS
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;	

SELECT
	A.[USER_NO]
,	A.[USER_NM]
,	A.[ID]
,	A.[PW]
,	A.[HDPH_NO]
,	A.[EMAIL]
,	A.LAST_CHNG_DT
,	A.LAST_USER_NO
FROM DBO.USERS A
WHERE A.[IS_DEL] = 0
AND A.[USER_NO] = @USER_NO
;
